services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bookstoreDB'
      - 'POSTGRES_PASSWORD=123@Mudar'
      - 'POSTGRES_USER=marreco'
    ports:
      - '5431:5432'
